refactor nodata
bandprotocol/cosmoscan pull request #124
Opened 2021-11-02 13:45 UTC by pangthebabydustbunny

2021-11-04 17:58 UTC, evilpeach commented
Please fix the conflict.

2021-11-07 21:53 UTC, pangthebabydustbunny commented
> Please fix the conflict.

fixed ka

2021-11-12 07:50 UTC, evilpeach requested changes

2021-11-12 07:50 UTC, evilpeach commented on src/components/LatestRequests.re
> +           src={isDarkMode ? Images.noDataDark : Images.noDataLight}
alt?

2021-11-12 07:50 UTC, evilpeach commented on src/pages/DataSourceHomePage.re
> +                 src={isDarkMode ? Images.noOracleDark : Images.noOracleLight}
alt?

2021-11-12 07:50 UTC, evilpeach commented on src/pages/OracleScriptHomePage.re
> +                 src={isDarkMode ? Images.noOracleDark : Images.noOracleLight}
alt?

2021-11-12 07:50 UTC, evilpeach commented on src/utils/Format.re
> +              (acc, ch, idx) => idx mod 3 == 0 && idx !== 0 ? ch ++ "," ++ acc : ch ++ acc,
mod 3 === 0

2021-11-12 07:50 UTC, evilpeach commented on src/reusable/Select.re
> +         }}
I think the old is ok.

2021-11-15 03:25 UTC, pzshine approved these changes

2021-11-15 03:54 UTC, evilpeach approved these changes

2021-11-15 03:54 UTC, merged