Fix ibc get list slow
bandprotocol/cosmoscan pull request #126
Opened 2021-11-07 18:52 UTC by evilpeach

2021-11-09 09:54 UTC, pzshine requested changes

2021-11-09 09:54 UTC, pzshine commented on src/subscriptions/IBCSub.re
>              IncomingPacketsConfig.makeVariables(
i'm not sure it might need to have interval or policy to make it realtime?

2021-11-09 09:54 UTC, pzshine commented on src/subscriptions/IBCSub.re
>              OutgoingPacketsConfig.makeVariables(
This is too.

2021-11-18 10:06 UTC, evilpeach commented
Moved to #136

2021-11-18 10:06 UTC, closed without merging