Verify tag
bandprotocol/cosmoscan pull request #130
Opened 2021-11-11 06:37 UTC by pangthebabydustbunny

2021-11-11 06:44 UTC, evilpeach requested changes

2021-11-11 06:44 UTC, evilpeach commented on src/pages/AccountIndexPage.re
> +  let addressTag = address->Address.toBech32->VerifyAccount.parseAddressName;
1. Move `Address.toBech32` to `VerifiedAccount.re`
2. Change `parseAddressName` to `getNameOpt`.
3. Change VerifyAccount to VerifiedAccount.

2021-11-11 06:44 UTC, evilpeach commented on src/reusable/AddressRender.re
> +  let fullAddress = prefix ++ noPrefixAddress;
It's no need to use it. Just use address from prop.

2021-11-11 06:44 UTC, evilpeach commented on src/utils/VerifyAccount.re
> +  fun
Use `Address.toBech32` here

2021-11-11 06:44 UTC, evilpeach commented on src/reusable/AddressRender.re
> +           ? switch (addressTag) {
Use like this
```
switch(addressTagOpt, label) {
| (Some(tag), true) => <span> tag->React.string </span>
| _ => <>
                 <span className=Styles.prefix> {prefix |> React.string} </span>
                 {noPrefixAddress |> React.string}
               </>
}

```

2021-11-12 08:01 UTC, pzshine approved these changes
LGTM

2021-11-16 05:09 UTC, evilpeach requested changes

2021-11-16 05:09 UTC, evilpeach commented on src/reusable/AddressRender.re
> +      ~tag=true,
I think we should use `~showName`

2021-11-16 05:09 UTC, evilpeach commented on src/reusable/AddressRender.re
> +  let addressTagOpt = address->VerifiedAccount.getNameOpt;
Remove this one.

2021-11-16 05:09 UTC, evilpeach commented on src/reusable/AddressRender.re
> +        {switch (addressTagOpt, tag) {
Replace `addressTagOpt` with `address->VerifiedAccount.getNameOpt`

2021-11-16 05:09 UTC, evilpeach commented on src/reusable/AddressRender.re
> +         | (Some(tag), true) => <span> tag->React.string </span>
Use `name` instead of `tag`

2021-11-16 05:09 UTC, evilpeach commented on src/pages/AccountIndexPage.re
> +  let addressTag = address->VerifiedAccount.getNameOpt;
Remove this one and move to switch case.

2021-11-16 05:09 UTC, evilpeach commented on src/pages/AccountIndexPage.re
> +                 | Some(v) =>
name

2021-11-16 05:09 UTC, evilpeach commented on src/pages/AccountIndexPage.re
> +                {switch (addressTag) {
move get function to here.

2021-11-17 04:06 UTC, evilpeach approved these changes

2021-11-17 04:07 UTC, merged