Show req message
bandprotocol/cosmoscan pull request #140
Opened 2021-12-02 16:51 UTC by pangthebabydustbunny

![Uploading Screen Shot 2564-12-02 at 23.48.42.png…](light mode)

![Uploading Screen Shot 2564-12-02 at 23.51.17.png…](dark mode)

2021-12-03 08:58 UTC, evilpeach requested changes
![image](https://user-images.githubusercontent.com/14128977/144574470-f697a8df-9a0a-4d3f-b863-8741bf16f00b.png)
Let's use circle loading instead.

2021-12-03 09:00 UTC, evilpeach requested changes

2021-12-07 10:55 UTC, evilpeach requested changes

2021-12-07 10:55 UTC, evilpeach commented on src/components/oracle-script/OracleScriptExecuteResponse.re
> +           | None => <> <RequestFailedResult id /> </>
There is a case that ResolveStatus == Success and the result can't be decoded by OBI
https://github.com/bandprotocol/cosmoscan/blob/main/src/pages/RequestIndexPage.re#L570

2021-12-28 01:24 UTC, babybunn commented
![Uploading Screen Shot 2564-12-28 at 08.20.05.png…](https://user-images.githubusercontent.com/12908129/147517590-6783a24b-f851-49ab-a96e-3269fd2d608e.png)

The screenshot shows the output as "schema not found" just in the case of Resolve status equal to "Success" but the Obi can't be decoded.

2022-01-06 04:02 UTC, evilpeach requested changes

2022-01-06 04:02 UTC, evilpeach commented on src/components/oracle-script/OracleScriptExecuteResponse.re
> +         | Some({resolveStatus: _, id}) => <RequestFailedResult id />
It's no need to use `resolveStatus: _`

2022-01-10 03:48 UTC, evilpeach approved these changes

2022-01-10 06:24 UTC, merged