Create cosmoscan.yml
bandprotocol/cosmoscan pull request #143
Opened 2021-12-29 09:33 UTC by poomthiti

initial setup for github actions

2021-12-30 03:10 UTC, evilpeach requested changes
remove `.mp4` files and add to `.gitignore`

2021-12-30 03:10 UTC, evilpeach commented on package.json
> +}
add end line

2021-12-30 05:52 UTC, poomthiti commented on package.json
> +}
done with prettier krub

2022-01-03 16:51 UTC, evilpeach commented
Why does the test fail?

2022-01-04 05:27 UTC, poomthiti commented
> @poomthiti Why does the test fail?

[Laozi Testnet, As of 4 Jan 2022, 12:15pm]
1. Undelegate with WeStaking failed. [Error: invalid version]
2. Redelegate from [WeStaking, Cosmostation] to other validators failed. [Error: an error occurred]

Everthing works with StakeWithUs, maybe will perform test cases on it instead

2022-01-10 08:06 UTC, poomthiti commented
[Test Passed] Changed test case to perform on StakeWithUs

2022-01-11 13:40 UTC, evilpeach requested changes
add `.DS_Store` to .gitignore

2022-01-11 20:57 UTC, poomthiti commented
> add `.DS_Store` to .gitignore

Done krub

2022-01-12 20:03 UTC, evilpeach approved these changes

2022-02-01 05:03 UTC, merged