Add request not found switch case
bandprotocol/cosmoscan pull request #150
Opened 2022-01-25 10:37 UTC by poomthiti

1. add switch case to handle in case no request id is found
2. add img for dark and light mode

2022-01-26 02:18 UTC, evilpeach requested changes

2022-01-26 02:18 UTC, evilpeach commented on src/pages/RequestIndexPage.re
> +  | NoData =>
Let's change to this one
```
| NoData
| Error(_) => ...
```

2022-01-26 03:52 UTC, poomthiti commented on src/pages/RequestIndexPage.re
> +  | NoData =>
Done kub

2022-02-06 15:06 UTC, pzshine commented
![image](https://user-images.githubusercontent.com/17017699/152687170-310d69b6-679f-4b35-b399-cbd6bcd285b9.png)

![image](https://user-images.githubusercontent.com/17017699/152687204-143004cf-e204-47b4-9841-1fc7d205637c.png)


Can you adjust these 2 images to be same width (120x120)?

2022-02-07 09:04 UTC, poomthiti commented
> ![image](https://user-images.githubusercontent.com/17017699/152687170-310d69b6-679f-4b35-b399-cbd6bcd285b9.png)
> 
> ![image](https://user-images.githubusercontent.com/17017699/152687204-143004cf-e204-47b4-9841-1fc7d205637c.png)
> 
> Can you adjust these 2 images to be same width (120x120)?

done krub, please kindly give it a look

2022-02-08 09:40 UTC, babybunn approved these changes

2022-02-08 09:57 UTC, babybunn approved these changes

2022-02-09 09:21 UTC, pzshine approved these changes

2022-02-09 11:28 UTC, babybunn approved these changes

2022-02-09 11:28 UTC, babybunn approved these changes

2022-02-09 11:29 UTC, merged